# Sleep Mode Configuration
sleep_mode:
  enabled: true
  close_browser: true  # Completely close browser during sleep
  wake_buffer: 300  # Wake up 5 minutes before active hours (seconds)
  sleep_buffer: 300  # Go to sleep 5 minutes after inactive hours (seconds)
  
  # Optional: Different schedule for weekends
  weekend_override:
    enabled: true
    start: 9  # 9:00 AM
    end: 3     # 3:00 AM
    
  # Browser restart settings
  restart:
    delay_after_close: 5  # Seconds to wait after closing before marking as complete
    delay_before_open: 5  # Seconds to wait before reopening browser
    max_retries: 3  # Max retries if browser fails to restart
    
  # Notifications
  notifications:
    on_sleep: true
    on_wake: true
    include_duration: true
    
# Global Configuration
active_hours:
  start: 8  # 8:00 AM
  end: 2    # 2:00 AM (next day)
  
  # Optional: Randomize start/end times slightly for more human behavior
  randomize:
    enabled: true
    max_variance: 15  # minutes

debug_mode: false
discord_webhook: ""

# Dashboard Configuration
dashboard:
  enabled: true
  host: "127.0.0.1"  # Use 0.0.0.0 to allow external access
  port: 8080
  
# Server Configuration
server:
  base_url: "https://it94.tribals.it"
  login_url: "https://www.tribals.it"
  village_id: 0  # Your village ID
  
# Browser Configuration
browser:
  headless: false
  slow_mo: 0
  user_data_dir: "./browser_data"
  viewport:
    width: 1600
    height: 900
  # Authentic Chrome settings
  chrome_version: "138"
  platform: "macOS"
  
# Anti-Detection Configuration
anti_detection:
  enabled: true
  random_user_agents: false  # Use specific UA for your session
  simulate_human_behavior: true
  random_breaks:
    enabled: true
    min_duration: 60  # seconds
    max_duration: 600  # seconds
    frequency: 0.1  # chance per hour
  mouse_movement:
    natural_curves: true
    random_movements: true
    movement_before_actions: 0.3  # 30% chance
  typing:
    variable_speed: true
    typo_chance: 0.01  # 1% chance
    thinking_pauses: true
  reading:
    simulate_reading: true
    words_per_minute_min: 200
    words_per_minute_max: 300
  fatigue:
    enabled: true
    multiplier_per_hour: 0.1  # 10% slower per hour
  network:
    random_referer: true
    authentic_headers: true
    cache_behavior: true

# Session Configuration
session:
  cookies:
    # These will be set automatically after login
    cid: ""
    locale: "en-US"
    mobile_mapsize: "14x16"
    global_village_id: ""
    websocket_available: "true"
  
# Automation Scripts Configuration
scripts:
  auto_buyer:
    enabled: false
    min_pp: 3000
    min_stock: 64
    post_buy_delay: 4800
    check_interval: 5000
    
  auto_farmer:
    enabled: false
    interval_seconds: 1200
    plan_delay: 700
    icon_start_delay: 1000
    icon_click_interval: 300
    
  auto_scavenger:
    enabled: true
    base_interval_seconds: 900
    interval_jitter_seconds: 90
    click_min_delay: 200
    click_max_delay: 800
    

# Captcha Configuration
captcha:
  max_retries: 2  # Reduced to fail faster on multi-challenge
  solver_timeout: 300  # 5 minutes for manual solving
  detection_interval: 2000
  response_timeout: 180  # 3 minutes for auto solving
  screenshot_timeout: 60  # 1 minute for screenshots
  auto_solve_enabled: true  # Set to false to always use manual
  
# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "tribals_bot.log"
  
# Request Configuration
request:
  headers:
    # These headers will be used for all requests
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
    Accept-Language: "it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7"
    Accept-Encoding: "gzip, deflate, br, zstd"
    Cache-Control: "no-cache"
    Pragma: "no-cache"
    Sec-CH-UA: '"Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"'
    Sec-CH-UA-Mobile: "?0"
    Sec-CH-UA-Platform: '"macOS"'
  timeout: 30000  # 30 seconds
  retry_attempts: 3
  retry_delay: 1000  # 1 second